url: "https://simonomi.dev"
baseurl: "/fftechwiki"
theme: null # remove default minima theme

strict_front_matter: true

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .jj
  - README.md

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      permalink: "/:path/:basename/index"
